### ISSUE TITLE
Improve ccache hit rate in CI

### ISSUE THREAD

**Issue by james-d-mitchell** [semigroups/Semigroups#830]
That could actually be. In GAP I've for various reasons "split" the caches and it seems to work well / better. Perhaps something to try for you, too? This is the syntax we used:
```
      - name: "Setup ccache"
        if: ${{ runner.os != 'Windows' }}
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          override_cache_key: ${{ runner.os }}-${{ hashFiles('extra.flags') }}-${{ github.ref }}
          override_cache_key_fallback: ${{ runner.os }}-${{ hashFiles('extra.flags') }}

```

Clearly you'll want to adjust this a bit. Maybe this would work:
```
      - name: "Setup ccache"
        if: ${{ runner.os != 'Windows' }}
        uses: Chocobo1/setup-ccache-action@v1
        with:
          update_packager_index: false
          override_cache_key: ${{ runner.os }}-${{ matrix.gap-branch }}-${{ matrix.ABI }}-${{ github.ref }}
          override_cache_key_fallback: ${{ runner.os }}-${{ matrix.gap-branch }}-${{ matrix.ABI }}

```

_Originally posted by @fingolfin in https://github.com/semigroups/Semigroups/issues/821#issuecomment-1108334585_
